steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/expense-bot:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expense-bot:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'expense-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/expense-bot:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'BOT_TYPE=telegram,TELEGRAM_BOT_TOKEN=$_TELEGRAM_BOT_TOKEN,GOOGLE_SHEETS_ID=$_GOOGLE_SHEETS_ID,GOOGLE_CLIENT_EMAIL=$_GOOGLE_CLIENT_EMAIL,GOOGLE_PRIVATE_KEY=$_GOOGLE_PRIVATE_KEY'

images:
  - 'gcr.io/$PROJECT_ID/expense-bot:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
